name: Auto-Merge Documentation Updates

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - 'README.md'

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Auto-Merge
        uses: pascalgn/automerge-action@v0.16.2
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          MERGE_LABELS: ""
          MERGE_METHOD: "squash"
          MERGE_DELETE_BRANCH: "true"
          MERGE_COMMIT_MESSAGE: "Auto-Merge Documentation Updates"
          MERGE_RETRIES: "3"
          MERGE_RETRY_SLEEP: "5000"
          UPDATE_LABELS: ""
          UPDATE_METHOD: rebase