name: Generate React Documentation

on:
  push:
    branches:  
      - main
    paths:
      - 'frontend/attendance-app/src/*.ts'
      - 'frontend/attendance-app/src/*.tsx'

permissions:
  contents: write
  pull-requests: write

jobs:
  generate_docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Choose a suitable Node.js version

      - name: Install dependencies
        run: npm install --save-dev react-docgen react-docgen-markdown-renderer

      - name: Generate Markdown documentation
        run: react-docgen src/components -o docs/components.md --pretty --markdown-renderer react-docgen-markdown-renderer

      - name: Setup Git
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

      - name: Delete the update-documentation-front branch if it exists
        run: |
          git fetch origin
          if git branch -r | grep -q "origin/update-documentation-front"; then
            git push origin --delete update-documentation-front
          fi
      - name: Create and switch to the update-documentation-front branch
        run: |
          git checkout main
          git pull origin main
          git checkout -b update-documentation-front

      - name: Commit and Push Documentation
        run: |
          git add README.md
          git commit -m "Update documentation" -a || echo "No changes to commit"
          git remote set-url origin https://x-access-token:${{ secrets.TOKEN }}@github.com/${{ github.repository }}
          git push origin update-documentation-front

      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.TOKEN }}
          pr_title: "Update Documentation"
          pr_body: "Automatically generated documentation update"
          destination_branch: "main"
          source_branch: "update-documentation"