name: Generate Documentation

on:
  push:
    branches:
      - main
    paths:
      - 'terraform/*.tf'
      - 'lambda_functions/*.py'
      - 'tests/*.py'
      - '.github/workflows/generate-docs.yml'
      - 'docs/*'

permissions:
  contents: write

jobs:
  documentation:
    name: Generate Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Terraform-docs
        run: |
          wget https://github.com/terraform-docs/terraform-docs/releases/download/v0.17.0/terraform-docs-v0.17.0-linux-amd64.tar.gz
          tar -xzf terraform-docs-v0.17.0-linux-amd64.tar.gz
          sudo mv terraform-docs /usr/local/bin

      - name: Generate Terraform Documentation
        run: |
          terraform-docs markdown table ./terraform > TERRAFORM.md

      - name: Install Sphinx, m2r2, and sphinx-markdown-builder for Python Documentation
        run: |
          pip install sphinx m2r2 sphinx-markdown-builder

      - name: Generate Python Documentation
        run: |
          sphinx-apidoc -o docs/source ./lambda_functions
          sphinx-apidoc -o docs/source ./tests --append-syspath
          sphinx-build -b markdown docs/source docs/build/markdown
          find docs/build/markdown -name '*.md' -exec cat {} + > PYTHON.md

      - name: Combine Documentation into Single Markdown File
        run: |
          echo -e "# Project Documentation" > README.md
          echo -e "\n# Terraform Documentation\n" >> README.md
          cat TERRAFORM.md >> README.md
          echo -e "\n# Python Documentation\n" >> README.md
          cat PYTHON.md >> README.md

      - name: Display Documentation
        run: |
          cat README.md

      - name: Commit and Push Documentation
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git checkout -b update-docs
          git add README.md
          git commit -m "Update documentation" -a || echo "No changes to commit"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git push origin update-docs

      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: "Update Documentation"
          pr_body: "Automatically generated documentation update"
          destination_branch: "main"
          source_branch: "update-docs"
