name: Generate Documentation

on:
  push:
    branches:
      - main
    paths:
      - 'terraform/*.tf'
      - 'lambda_functions/*.py'
      - 'tests/*.py'
      - '.github/workflows/generate-docs.yml'
      - 'docs/src/*'
      - 'frontend/attendance-app/src/*'

permissions:
  contents: write
  pull-requests: write

jobs:
  documentation:
    name: Generate Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Terraform-docs
        run: |
          wget https://github.com/terraform-docs/terraform-docs/releases/download/v0.17.0/terraform-docs-v0.17.0-linux-amd64.tar.gz
          tar -xzf terraform-docs-v0.17.0-linux-amd64.tar.gz
          sudo mv terraform-docs /usr/local/bin

      - name: Generate Terraform Documentation
        run: |
          terraform-docs markdown table ./terraform > TERRAFORM.md

      - name: Install Sphinx, m2r2, and sphinx-markdown-builder for Python Documentation
        run: |
          pip install sphinx m2r2 sphinx-markdown-builder boto3 pytest

      - name: Generate Python Documentation
        run: |
          sphinx-apidoc -o docs/source ./lambda_functions --force
          sphinx-apidoc -o docs/source ./tests --append-syspath --force
          sphinx-build -b markdown docs/source docs/build/markdown
          find docs/build/markdown -name '*.md' -exec cat {} + > PYTHON.md

      - name: Install Node Dependencies
        run: npm install --save-dev typedoc

      - name: Generate React Documentation
        run: |
          cd frontend/attendance-app/src
          npx typedoc
          # cd ../../../
          # mv frontend/attendance-app/frontend-docs frontend-docs

      - name: Combine Documentation into Single Markdown File
        run: |
          echo -e "# Project Documentation" > README.md
          echo -e "\n# Terraform Documentation\n" >> README.md
          cat TERRAFORM.md >> README.md
          echo -e "\n# Python Documentation\n" >> README.md
          cat PYTHON.md >> README.md

      - name: Setup Git
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

      - name: Delete the update-documentation branch if it exists
        run: |
          git fetch origin
          if git branch -r | grep -q "origin/update-documentation"; then
            git push origin --delete update-documentation
          fi

      - name: Create and switch to the update-documentation branch
        run: |
          git checkout main
          git pull origin main
          git checkout -b update-documentation

      - name: Commit and Push Documentation
        run: |
          git add README.md
          git commit -m "Update documentation" -a || echo "No changes to commit"
          git remote set-url origin https://x-access-token:${{ secrets.TOKEN }}@github.com/${{ github.repository }}
          git push origin update-documentation

      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.TOKEN }}
          pr_title: "Update Documentation"
          pr_body: "Automatically generated documentation update"
          destination_branch: "main"
          source_branch: "update-documentation"
