name: Deploy Lambda Functions

on:
  push:
    branches:
      - main
    paths:
      - 'lambda_functions/*.py'

jobs:
  deploy-lambda:
    name: Deploy Lambda Functions
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1

    - name: Deploy Lambda Functions
      run: |
        for file in lambda_functions/*.py; do
          function_name=$(basename $file .py)
          echo "Deploying $function_name..."
          zip -j "$function_name.zip" "$file"
          aws lambda update-function-code --function-name $function_name --zip-file fileb://"$function_name.zip"
        done
