  name: Lambda Function Tests

  on:
    push:
      branches:
        - main
    pull_request:
      branches:
        - main

  jobs:
    test-lambda-functions:
      name: Test Lambda Functions
      runs-on: ubuntu-latest

      steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Set fake AWS credentials
        run: |
          echo "AWS_ACCESS_KEY_ID=testing" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=testing" >> $GITHUB_ENV
          echo "AWS_REGION=eu-central-1" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r tests/requirements.txt

      - name: Run tests
        run: |
          pytest tests/
